# Corrected hello.yml file for GitHub Actions
# This file defines a simple workflow that runs on pushes to the main branch

name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest # This is the corrected line
    steps:
      - name: Say hello
        run: echo "Hello World!"
      - name: Print date
        run: date
      - name: List files
        run: ls -l
