name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Check style
        run: npm run eslint
      - name: Build
        run: npm run build
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          command: npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:5000
      - name: Test
        run: npm test

  deploy: # Independent deployment job
    needs: simple_deployment_pipeline
    runs-on: ubuntu-latest
    # This job only runs on a push to the main branch
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Deploy
        run: curl ${{ secrets.RENDER_DEPLOY_HOOK }}

  tag_release:
    # This job depends on the successful completion of the 'deploy' job
    needs: deploy
    runs-on: ubuntu-latest
    # This job also only runs on a push to the main branch
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      # The checkout action is needed to access the repository's code and git history
      - uses: actions/checkout@v4
        with:
          # Fetches all history for all branches and tags, which is required for the tagging action
          fetch-depth: '0'

      # This step uses the specified third-party action to handle versioning
      - name: Bump version and push tag
        # Using a recent and specific version of the action is a best practice.
        uses: anothrNick/github-tag-action@1.73.0
        env:
          # The GITHUB_TOKEN is automatically created by Actions and needs write permissions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # This sets the default version increment to a patch (e.g., v1.0.0 -> v1.0.1)
          DEFAULT_BUMP: patch
          # Optional: Use this to test the action without creating a real tag
          # DRY_RUN: true
